import type { GearDef, GearSetDef, Rarity, Slot } from "./types";

export const SLOTS: Slot[] = [
  "helmet",
  "chestplate",
  "leggings",
  "boots",
  "weapon",
];

export const SLOT_LABELS: Record<Slot, string> = {
  helmet: "Helmet",
  chestplate: "Chestplate",
  leggings: "Leggings",
  boots: "Boots",
  weapon: "Weapon",
};

export const RARITY_ORDER: Rarity[] = [
  "scrap",
  "forged",
  "enchanted",
  "mythic",
  "relic",
];

export const RARITY_LABELS: Record<Rarity, string> = {
  scrap: "Scrap",
  forged: "Forged",
  enchanted: "Enchanted",
  mythic: "Mythic",
  relic: "Relic",
};

export const RARITY_COLORS: Record<Rarity, string> = {
  scrap: "#9ca3af",
  forged: "#34d399",
  enchanted: "#22d3ee",
  mythic: "#fbbf24",
  relic: "#fb7185",
};

export const DUPLICATE_COINS: Record<Rarity, number> = {
  scrap: 8,
  forged: 18,
  enchanted: 40,
  mythic: 90,
  relic: 200,
};

export const GEAR_SETS: GearSetDef[] = [
  {
    id: "scrap",
    name: "Scrap Armor",
    bonusXpPct: 3,
    bonusCoins: 2,
    hue: 210,
  },
  {
    id: "frostbite",
    name: "Frostbite Vanguard",
    bonusXpPct: 6,
    bonusCoins: 4,
    hue: 195,
  },
  {
    id: "starlight",
    name: "Starlight Sorcerer Robes",
    bonusXpPct: 6,
    bonusCoins: 4,
    hue: 220,
  },
  {
    id: "sunfire",
    name: "Sunfire Paladin Armor",
    bonusXpPct: 10,
    bonusCoins: 8,
    hue: 35,
  },
  {
    id: "dragonguard",
    name: "Dragon Guard Mail",
    bonusXpPct: 10,
    bonusCoins: 8,
    hue: 10,
  },
  {
    id: "mech",
    name: "Titanium Mech Armor",
    bonusXpPct: 14,
    bonusCoins: 12,
    hue: 170,
  },
  {
    id: "shadow",
    name: "Shadow Realm Monarch",
    bonusXpPct: 14,
    bonusCoins: 12,
    hue: 200,
  },
  {
    id: "phantom",
    name: "Phantom Emperor",
    bonusXpPct: 18,
    bonusCoins: 16,
    hue: 340,
  },
];

/** Full hunt-able sets */
const SET_PIECES: GearDef[] = [
  // Scrap Armor — common hunt
  {
    id: "scrap-helmet",
    name: "Rusty Bucket Helm",
    slot: "helmet",
    setId: "scrap",
    rarity: "scrap",
    xpBonusPct: 1,
    coinBonus: 0,
    hue: 210,
    storePrice: 40,
  },
  {
    id: "scrap-chestplate",
    name: "Patchwork Chestplate",
    slot: "chestplate",
    setId: "scrap",
    rarity: "scrap",
    xpBonusPct: 1,
    coinBonus: 1,
    hue: 210,
    storePrice: 55,
  },
  {
    id: "scrap-leggings",
    name: "Dented Leg Plates",
    slot: "leggings",
    setId: "scrap",
    rarity: "scrap",
    xpBonusPct: 1,
    coinBonus: 0,
    hue: 210,
  },
  {
    id: "scrap-boots",
    name: "Mud-Stomper Boots",
    slot: "boots",
    setId: "scrap",
    rarity: "forged",
    xpBonusPct: 2,
    coinBonus: 1,
    hue: 210,
    storePrice: 70,
  },
  {
    id: "scrap-weapon",
    name: "Bent Nail Sword",
    slot: "weapon",
    setId: "scrap",
    rarity: "scrap",
    xpBonusPct: 2,
    coinBonus: 1,
    hue: 210,
  },

  // Frostbite Vanguard
  {
    id: "frostbite-helmet",
    name: "Glacier Visor",
    slot: "helmet",
    setId: "frostbite",
    rarity: "forged",
    xpBonusPct: 3,
    coinBonus: 1,
    hue: 195,
  },
  {
    id: "frostbite-chestplate",
    name: "Rimeplate Cuirass",
    slot: "chestplate",
    setId: "frostbite",
    rarity: "enchanted",
    xpBonusPct: 4,
    coinBonus: 2,
    hue: 195,
    storePrice: 220,
  },
  {
    id: "frostbite-leggings",
    name: "Icevein Greaves",
    slot: "leggings",
    setId: "frostbite",
    rarity: "forged",
    xpBonusPct: 3,
    coinBonus: 1,
    hue: 195,
  },
  {
    id: "frostbite-boots",
    name: "Snowstride Treads",
    slot: "boots",
    setId: "frostbite",
    rarity: "forged",
    xpBonusPct: 3,
    coinBonus: 1,
    hue: 195,
  },
  {
    id: "frostbite-weapon",
    name: "Frostfang Spear",
    slot: "weapon",
    setId: "frostbite",
    rarity: "enchanted",
    xpBonusPct: 5,
    coinBonus: 2,
    hue: 195,
  },

  // Starlight Sorcerer
  {
    id: "starlight-helmet",
    name: "Constellation Hood",
    slot: "helmet",
    setId: "starlight",
    rarity: "forged",
    xpBonusPct: 3,
    coinBonus: 1,
    hue: 220,
  },
  {
    id: "starlight-chestplate",
    name: "Nebula Robe",
    slot: "chestplate",
    setId: "starlight",
    rarity: "enchanted",
    xpBonusPct: 4,
    coinBonus: 2,
    hue: 220,
  },
  {
    id: "starlight-leggings",
    name: "Twilight Wraps",
    slot: "leggings",
    setId: "starlight",
    rarity: "forged",
    xpBonusPct: 3,
    coinBonus: 1,
    hue: 220,
    storePrice: 160,
  },
  {
    id: "starlight-boots",
    name: "Meteor Slippers",
    slot: "boots",
    setId: "starlight",
    rarity: "forged",
    xpBonusPct: 3,
    coinBonus: 1,
    hue: 220,
  },
  {
    id: "starlight-weapon",
    name: "Astral Staff",
    slot: "weapon",
    setId: "starlight",
    rarity: "enchanted",
    xpBonusPct: 5,
    coinBonus: 2,
    hue: 220,
  },

  // Sunfire Paladin
  {
    id: "sunfire-helmet",
    name: "Solar Crest Helm",
    slot: "helmet",
    setId: "sunfire",
    rarity: "enchanted",
    xpBonusPct: 5,
    coinBonus: 2,
    hue: 35,
  },
  {
    id: "sunfire-chestplate",
    name: "Dawnforge Breastplate",
    slot: "chestplate",
    setId: "sunfire",
    rarity: "mythic",
    xpBonusPct: 7,
    coinBonus: 3,
    hue: 35,
  },
  {
    id: "sunfire-leggings",
    name: "Radiant Poleyns",
    slot: "leggings",
    setId: "sunfire",
    rarity: "enchanted",
    xpBonusPct: 5,
    coinBonus: 2,
    hue: 35,
  },
  {
    id: "sunfire-boots",
    name: "Sunstep Sabatons",
    slot: "boots",
    setId: "sunfire",
    rarity: "enchanted",
    xpBonusPct: 5,
    coinBonus: 2,
    hue: 35,
    storePrice: 380,
  },
  {
    id: "sunfire-weapon",
    name: "Flarebrand Sword",
    slot: "weapon",
    setId: "sunfire",
    rarity: "mythic",
    xpBonusPct: 8,
    coinBonus: 4,
    hue: 35,
  },

  // Dragon Guard
  {
    id: "dragonguard-helmet",
    name: "Wyrmskull Helm",
    slot: "helmet",
    setId: "dragonguard",
    rarity: "enchanted",
    xpBonusPct: 5,
    coinBonus: 2,
    hue: 10,
  },
  {
    id: "dragonguard-chestplate",
    name: "Scalebane Mail",
    slot: "chestplate",
    setId: "dragonguard",
    rarity: "mythic",
    xpBonusPct: 7,
    coinBonus: 3,
    hue: 10,
    storePrice: 520,
  },
  {
    id: "dragonguard-leggings",
    name: "Talon-Guard Greaves",
    slot: "leggings",
    setId: "dragonguard",
    rarity: "enchanted",
    xpBonusPct: 5,
    coinBonus: 2,
    hue: 10,
  },
  {
    id: "dragonguard-boots",
    name: "Clawprint Boots",
    slot: "boots",
    setId: "dragonguard",
    rarity: "enchanted",
    xpBonusPct: 5,
    coinBonus: 2,
    hue: 10,
  },
  {
    id: "dragonguard-weapon",
    name: "Ember Drake Axe",
    slot: "weapon",
    setId: "dragonguard",
    rarity: "mythic",
    xpBonusPct: 8,
    coinBonus: 4,
    hue: 10,
  },

  // Titanium Mech
  {
    id: "mech-helmet",
    name: "Servo-Visor MK.II",
    slot: "helmet",
    setId: "mech",
    rarity: "mythic",
    xpBonusPct: 8,
    coinBonus: 4,
    hue: 170,
  },
  {
    id: "mech-chestplate",
    name: "Titanium Coreplate",
    slot: "chestplate",
    setId: "mech",
    rarity: "mythic",
    xpBonusPct: 9,
    coinBonus: 5,
    hue: 170,
  },
  {
    id: "mech-leggings",
    name: "Hydraulic Leg Assemblies",
    slot: "leggings",
    setId: "mech",
    rarity: "mythic",
    xpBonusPct: 8,
    coinBonus: 4,
    hue: 170,
  },
  {
    id: "mech-boots",
    name: "Thruster Boots",
    slot: "boots",
    setId: "mech",
    rarity: "mythic",
    xpBonusPct: 8,
    coinBonus: 4,
    hue: 170,
  },
  {
    id: "mech-weapon",
    name: "Plasma Cleaver",
    slot: "weapon",
    setId: "mech",
    rarity: "mythic",
    xpBonusPct: 10,
    coinBonus: 5,
    hue: 170,
    storePrice: 900,
  },

  // Shadow Realm Monarch
  {
    id: "shadow-helmet",
    name: "Umbral Crown",
    slot: "helmet",
    setId: "shadow",
    rarity: "mythic",
    xpBonusPct: 8,
    coinBonus: 4,
    hue: 200,
  },
  {
    id: "shadow-chestplate",
    name: "Voidweave Mantle",
    slot: "chestplate",
    setId: "shadow",
    rarity: "mythic",
    xpBonusPct: 9,
    coinBonus: 5,
    hue: 200,
  },
  {
    id: "shadow-leggings",
    name: "Nightfall Greaves",
    slot: "leggings",
    setId: "shadow",
    rarity: "mythic",
    xpBonusPct: 8,
    coinBonus: 4,
    hue: 200,
  },
  {
    id: "shadow-boots",
    name: "Silentstep Sabatons",
    slot: "boots",
    setId: "shadow",
    rarity: "mythic",
    xpBonusPct: 8,
    coinBonus: 4,
    hue: 200,
  },
  {
    id: "shadow-weapon",
    name: "Eclipse Scepter",
    slot: "weapon",
    setId: "shadow",
    rarity: "mythic",
    xpBonusPct: 10,
    coinBonus: 5,
    hue: 200,
  },

  // Phantom Emperor
  {
    id: "phantom-helmet",
    name: "Emperor’s Phantom Mask",
    slot: "helmet",
    setId: "phantom",
    rarity: "mythic",
    xpBonusPct: 10,
    coinBonus: 5,
    hue: 340,
  },
  {
    id: "phantom-chestplate",
    name: "Ghostfire Regalia",
    slot: "chestplate",
    setId: "phantom",
    rarity: "mythic",
    xpBonusPct: 11,
    coinBonus: 6,
    hue: 340,
  },
  {
    id: "phantom-leggings",
    name: "Wraithbone Legguards",
    slot: "leggings",
    setId: "phantom",
    rarity: "mythic",
    xpBonusPct: 10,
    coinBonus: 5,
    hue: 340,
  },
  {
    id: "phantom-boots",
    name: "Spectral Marchers",
    slot: "boots",
    setId: "phantom",
    rarity: "mythic",
    xpBonusPct: 10,
    coinBonus: 5,
    hue: 340,
  },
  {
    id: "phantom-weapon",
    name: "Soulrend Greatsword",
    slot: "weapon",
    setId: "phantom",
    rarity: "mythic",
    xpBonusPct: 12,
    coinBonus: 6,
    hue: 340,
  },
];

/** Good-but-not-great unmatched one-offs */
const WILD_PIECES: GearDef[] = [
  {
    id: "wild-courier-cap",
    name: "Courier’s Lucky Cap",
    slot: "helmet",
    setId: null,
    rarity: "forged",
    xpBonusPct: 2,
    coinBonus: 2,
    hue: 90,
    storePrice: 95,
  },
  {
    id: "wild-kitchen-apron",
    name: "Battle-Chef Apron",
    slot: "chestplate",
    setId: null,
    rarity: "forged",
    xpBonusPct: 2,
    coinBonus: 3,
    hue: 25,
    storePrice: 110,
  },
  {
    id: "wild-garden-knees",
    name: "Garden Sentinel Kneeguards",
    slot: "leggings",
    setId: null,
    rarity: "enchanted",
    xpBonusPct: 4,
    coinBonus: 2,
    hue: 130,
  },
  {
    id: "wild-sock-slippers",
    name: "Silent Sock Slippers",
    slot: "boots",
    setId: null,
    rarity: "forged",
    xpBonusPct: 2,
    coinBonus: 2,
    hue: 320,
  },
  {
    id: "wild-broom-lance",
    name: "Broomhandle Lance",
    slot: "weapon",
    setId: null,
    rarity: "scrap",
    xpBonusPct: 1,
    coinBonus: 1,
    hue: 40,
    storePrice: 35,
  },
  {
    id: "wild-choresmith-hammer",
    name: "Choresmith Hammer",
    slot: "weapon",
    setId: null,
    rarity: "enchanted",
    xpBonusPct: 4,
    coinBonus: 3,
    hue: 45,
    storePrice: 250,
  },
  {
    id: "wild-raincloak",
    name: "Puddleproof Raincloak",
    slot: "chestplate",
    setId: null,
    rarity: "forged",
    xpBonusPct: 3,
    coinBonus: 1,
    hue: 200,
  },
  {
    id: "wild-focus-band",
    name: "Homework Focus Band",
    slot: "helmet",
    setId: null,
    rarity: "enchanted",
    xpBonusPct: 5,
    coinBonus: 1,
    hue: 160,
  },
];

/** Ultra-rare Relic one-offs */
const RELIC_PIECES: GearDef[] = [
  {
    id: "relic-crown-first-chore",
    name: "Crown of the First Chore",
    slot: "helmet",
    setId: null,
    rarity: "relic",
    xpBonusPct: 15,
    coinBonus: 8,
    hue: 48,
  },
  {
    id: "relic-aegis-tidy",
    name: "Aegis of Eternal Tidy",
    slot: "chestplate",
    setId: null,
    rarity: "relic",
    xpBonusPct: 16,
    coinBonus: 10,
    hue: 48,
  },
  {
    id: "relic-legends-stride",
    name: "Legends’ Stride Greaves",
    slot: "leggings",
    setId: null,
    rarity: "relic",
    xpBonusPct: 14,
    coinBonus: 8,
    hue: 48,
  },
  {
    id: "relic-boots-of-dawn",
    name: "Boots of the Rising Dawn",
    slot: "boots",
    setId: null,
    rarity: "relic",
    xpBonusPct: 14,
    coinBonus: 8,
    hue: 48,
  },
  {
    id: "relic-blade-of-order",
    name: "Blade of Household Order",
    slot: "weapon",
    setId: null,
    rarity: "relic",
    xpBonusPct: 18,
    coinBonus: 12,
    hue: 48,
  },
];

export const ALL_GEAR: GearDef[] = [
  ...SET_PIECES,
  ...WILD_PIECES,
  ...RELIC_PIECES,
];

export const GEAR_BY_ID: Record<string, GearDef> = Object.fromEntries(
  ALL_GEAR.map((g) => [g.id, g]),
);

export const STORE_CHESTS = {
  common: { price: 75, label: "Common Chest", type: "normal" as const },
  legendary: {
    price: 400,
    label: "Legendary Chest",
    type: "legendary" as const,
  },
};

export const STORE_GEAR = ALL_GEAR.filter((g) => g.storePrice != null);

export function getSetPieces(setId: string): GearDef[] {
  return ALL_GEAR.filter((g) => g.setId === setId);
}
