import type { AvatarId, Quest, QuestCategory } from "./types";

export const QUEST_CATEGORIES: Array<"All Quests" | QuestCategory> = [
  "All Quests",
  "Bedroom",
  "Pets",
  "School Prep",
  "Kitchen",
  "Laundry",
  "Cleaning",
  "Outdoor",
];

export const AVATARS: Array<{
  id: AvatarId;
  name: string;
  blurb: string;
  emoji: string;
}> = [
  {
    id: "knight",
    name: "Knight",
    blurb: "Shield raised. Chores conquered.",
    emoji: "🛡️",
  },
  {
    id: "wizard",
    name: "Wizard",
    blurb: "Spells of tidy magic.",
    emoji: "🔮",
  },
  {
    id: "archer",
    name: "Archer",
    blurb: "Quick aim. Clean shot.",
    emoji: "🏹",
  },
  {
    id: "dragon-rider",
    name: "Dragon Rider",
    blurb: "Soar above the mess.",
    emoji: "🐉",
  },
  {
    id: "berserker",
    name: "Berserker",
    blurb: "Raw power. Absolute tidy rage.",
    emoji: "🪓",
  },
];

export const STORY_PANELS = [
  {
    title: "The Realm Grows Dim",
    text: "In the Kingdom of Home, shadows of clutter creep across every hall. Dust goblins laugh. Sock dragons nest in corners. The old heroes… have vanished.",
  },
  {
    title: "A Call From the Vault",
    text: "Deep beneath the house, the Treasure Vault stirs. It needs a champion — someone brave enough to turn everyday chores into legendary raids.",
  },
  {
    title: "Quests Await",
    text: "Each chore is a quest. Complete them to earn XP, gold, and chests of forgotten armor forged for heroes like you.",
  },
  {
    title: "Gear of the Ancients",
    text: "Collect rare sets. Equip helmets, blades, and boots. Hunt Relics so powerful only the tidiest champions ever see them.",
  },
  {
    title: "Your Legend Begins",
    text: "The Quest Board is open. Choose your hero. Level up. Open chests. Become the champion this realm has been waiting for.",
  },
];

export const QUESTS: Quest[] = [
  // —— Bedroom ——
  {
    id: "bed-castle",
    name: "Make Your Bed Castle",
    category: "Bedroom",
    difficulty: "quick",
    minutes: 2,
    xp: 50,
    coins: 10,
    goal: "Pull up the covers, straighten the pillows, and smooth the blankets like a royal bedchamber.",
    icon: "🛏️",
  },
  {
    id: "toy-raid",
    name: "Toy Realm Cleanup Raid",
    category: "Bedroom",
    difficulty: "epic",
    minutes: 10,
    xp: 100,
    coins: 25,
    goal: "Return toys, blocks, and books to their bins and shelves until the floor is clear.",
    icon: "🧸",
  },
  {
    id: "bookshelf-order",
    name: "Scroll Shelf Order",
    category: "Bedroom",
    difficulty: "quick",
    minutes: 5,
    xp: 55,
    coins: 12,
    goal: "Organize a bookshelf or media cabinet so every item stands upright and tidy.",
    icon: "📚",
  },
  {
    id: "donate-sort",
    name: "Treasure Sort for Sharing",
    category: "Bedroom",
    difficulty: "epic",
    minutes: 10,
    xp: 85,
    coins: 20,
    goal: "Sort a shared toy box — set aside broken pieces and treasures ready to donate.",
    icon: "🎁",
  },

  // —— Pets ——
  {
    id: "feed-beast",
    name: "Feed the Loyal Beast",
    category: "Pets",
    difficulty: "quick",
    minutes: 2,
    xp: 50,
    coins: 12,
    goal: "Fill the water bowl or place pre-measured food (with a grown-up nearby).",
    icon: "🐾",
    maxPerDay: 2,
    cooldownHours: 5,
  },
  {
    id: "pet-patrol",
    name: "Pet Path Patrol",
    category: "Pets",
    difficulty: "quick",
    minutes: 5,
    xp: 60,
    coins: 15,
    goal: "A short walk, playtime, or gentle brushing — keep your beast happy.",
    icon: "🐕",
  },
  {
    id: "groom-hound",
    name: "Groom the Loyal Hound",
    category: "Pets",
    difficulty: "quick",
    minutes: 8,
    xp: 70,
    coins: 16,
    goal: "Brush or gently wash the dog — fur tidy, paws clean, good boy earned.",
    icon: "🪥",
    maxPerDay: 1,
  },
  {
    id: "play-hound",
    name: "Play with the Hound",
    category: "Pets",
    difficulty: "quick",
    minutes: 10,
    xp: 75,
    coins: 18,
    goal: "Fetch, tug, or backyard play — burn energy and share a happy romp.",
    icon: "🎾",
    maxPerDay: 1,
  },

  // —— School Prep / personal / entry ——
  {
    id: "backpack",
    name: "Backpack of Holding",
    category: "School Prep",
    difficulty: "quick",
    minutes: 3,
    xp: 45,
    coins: 10,
    goal: "Pack homework, books, and tomorrow’s needs into your bag.",
    icon: "🎒",
  },
  {
    id: "outfit",
    name: "Outfit of Power",
    category: "School Prep",
    difficulty: "quick",
    minutes: 2,
    xp: 35,
    coins: 8,
    goal: "Lay out clothes and shoes for the next day.",
    icon: "👕",
  },
  {
    id: "lunch-scroll",
    name: "Lunch Scroll Prep",
    category: "School Prep",
    difficulty: "quick",
    minutes: 5,
    xp: 55,
    coins: 12,
    goal: "Help pack or set up lunch and snack for school.",
    icon: "🍎",
  },
  {
    id: "cloak-hook",
    name: "Cloak & Boot Hook",
    category: "School Prep",
    difficulty: "quick",
    minutes: 2,
    xp: 35,
    coins: 8,
    goal: "Hang your coat and place your shoes in the cubby or on a low hook.",
    icon: "🧥",
  },
  {
    id: "tooth-shine",
    name: "Tooth Shine Ritual",
    category: "School Prep",
    difficulty: "quick",
    minutes: 2,
    xp: 40,
    coins: 8,
    goal: "Brush your teeth, then put the toothbrush and toothpaste away.",
    icon: "🪥",
    maxPerDay: 2,
    cooldownHours: 5,
  },

  // —— Kitchen / dining / food ——
  {
    id: "dish-knight",
    name: "Dish Knight Duty",
    category: "Kitchen",
    difficulty: "quick",
    minutes: 5,
    xp: 70,
    coins: 18,
    goal: "Clear your dishes to the sink or dishwasher.",
    icon: "🍽️",
  },
  {
    id: "table-set",
    name: "Feast Table Setup",
    category: "Kitchen",
    difficulty: "quick",
    minutes: 4,
    xp: 50,
    coins: 12,
    goal: "Set the table with napkins, plastic cups, and other non-breakable gear.",
    icon: "🍴",
  },
  {
    id: "dishwasher-load",
    name: "Dishwasher Dungeon Run",
    category: "Kitchen",
    difficulty: "quick",
    minutes: 6,
    xp: 70,
    coins: 16,
    goal: "Load or unload the dishwasher — only non-sharp, non-breakable items.",
    icon: "🫧",
  },
  {
    id: "pantry-haul",
    name: "Pantry Haul Quest",
    category: "Kitchen",
    difficulty: "quick",
    minutes: 5,
    xp: 55,
    coins: 14,
    goal: "Help carry grocery bags in and put pantry items on lower shelves.",
    icon: "🛒",
  },
  {
    id: "snack-forge",
    name: "Snack Forge",
    category: "Kitchen",
    difficulty: "quick",
    minutes: 5,
    xp: 60,
    coins: 14,
    goal: "Make a simple snack or lunch — sandwich, cereal, or similar (grown-up ok nearby).",
    icon: "🥪",
  },
  {
    id: "grocery-scout",
    name: "Market Scout Mission",
    category: "Kitchen",
    difficulty: "epic",
    minutes: 10,
    xp: 80,
    coins: 18,
    goal: "At the store, help find specific items from the grocery list.",
    icon: "📝",
  },
  {
    id: "clear-feast",
    name: "Clear the Feast",
    category: "Kitchen",
    difficulty: "quick",
    minutes: 5,
    xp: 55,
    coins: 12,
    goal: "Clear the table after dinner — napkins, plates, and leftover gear.",
    icon: "🧺",
  },

  // —— Laundry ——
  {
    id: "sock-dragon",
    name: "Sock Dragon Taming",
    category: "Laundry",
    difficulty: "quick",
    minutes: 3,
    xp: 40,
    coins: 8,
    goal: "Gather stray socks and get them into the hamper.",
    icon: "🧦",
  },
  {
    id: "hamper-sort",
    name: "Hamper Color Sort",
    category: "Laundry",
    difficulty: "quick",
    minutes: 4,
    xp: 45,
    coins: 10,
    goal: "Sort dirty clothes into darks and lights, then place them in the hamper.",
    icon: "🧺",
  },
  {
    id: "sock-match",
    name: "Sock Pair Pact",
    category: "Laundry",
    difficulty: "quick",
    minutes: 4,
    xp: 45,
    coins: 10,
    goal: "Match clean socks into pairs after they come out of the dryer.",
    icon: "👯",
  },
  {
    id: "fold-linens",
    name: "Banner Fold Ritual",
    category: "Laundry",
    difficulty: "quick",
    minutes: 6,
    xp: 65,
    coins: 15,
    goal: "Fold towels, pillowcases, and your own t-shirts.",
    icon: "🧺",
  },
  {
    id: "drawer-stash",
    name: "Drawer Stash Quest",
    category: "Laundry",
    difficulty: "quick",
    minutes: 5,
    xp: 55,
    coins: 12,
    goal: "Put your clean, folded clothes away in the correct drawers.",
    icon: "👗",
  },

  // —— Cleaning ——
  {
    id: "crumb-goblin",
    name: "Crumb Goblin Sweep",
    category: "Cleaning",
    difficulty: "quick",
    minutes: 3,
    xp: 40,
    coins: 10,
    goal: "Wipe the dining table or counter after a meal with a damp cloth.",
    icon: "🧹",
  },
  {
    id: "kitchen-table-shine",
    name: "Kitchen Table Shine",
    category: "Cleaning",
    difficulty: "quick",
    minutes: 4,
    xp: 45,
    coins: 10,
    goal: "Clear the kitchen table, then wipe it clean until it shines.",
    icon: "🧽",
  },
  {
    id: "tv-stand-shine",
    name: "TV Stand Polish",
    category: "Cleaning",
    difficulty: "quick",
    minutes: 5,
    xp: 50,
    coins: 12,
    goal: "Clear remotes and clutter, then wipe the TV stand dust-free.",
    icon: "📺",
  },
  {
    id: "kitchen-counter-shine",
    name: "Kitchen Counter Crusade",
    category: "Cleaning",
    difficulty: "quick",
    minutes: 6,
    xp: 55,
    coins: 14,
    goal: "Clear the kitchen counters, then wipe them clean and dry.",
    icon: "🍽️",
  },
  {
    id: "dust-low",
    name: "Dust Goblin Banish",
    category: "Cleaning",
    difficulty: "quick",
    minutes: 5,
    xp: 50,
    coins: 12,
    goal: "Dust low surfaces — baseboards or coffee tables — with a soft cloth.",
    icon: "✨",
  },
  {
    id: "floor-sweep",
    name: "Floor Sweep Patrol",
    category: "Cleaning",
    difficulty: "quick",
    minutes: 5,
    xp: 55,
    coins: 12,
    goal: "Sweep the kitchen or entryway with a child-sized broom and dustpan.",
    icon: "🧹",
  },
  {
    id: "vacuum-living",
    name: "Living Room Vortex Raid",
    category: "Cleaning",
    difficulty: "epic",
    minutes: 10,
    xp: 90,
    coins: 20,
    goal: "Vacuum the living room floor — rugs, corners, and under the couch edge if you can reach.",
    icon: "🌪️",
  },
  {
    id: "wastebasket-run",
    name: "Wastebasket Courier",
    category: "Cleaning",
    difficulty: "quick",
    minutes: 4,
    xp: 45,
    coins: 10,
    goal: "Empty small bedroom or bathroom wastebaskets into the main trash.",
    icon: "🗑️",
  },
  {
    id: "bath-shine",
    name: "Mirror & Counter Shine",
    category: "Cleaning",
    difficulty: "quick",
    minutes: 5,
    xp: 55,
    coins: 14,
    goal: "Wipe bathroom counters and mirrors with a safe, non-toxic cleaner.",
    icon: "🪞",
  },

  // —— Outdoor / yard / errands ——
  {
    id: "trash-titan",
    name: "Trash Titan Banishment",
    category: "Outdoor",
    difficulty: "quick",
    minutes: 3,
    xp: 45,
    coins: 12,
    goal: "Take out the main trash bin to its pickup spot.",
    icon: "🗑️",
  },
  {
    id: "yard-scout",
    name: "Yard Realm Scout",
    category: "Outdoor",
    difficulty: "epic",
    minutes: 10,
    xp: 90,
    coins: 20,
    goal: "Quick outdoor tidy: toys in, leaves and sticks cleared in your zone.",
    icon: "🌳",
  },
  {
    id: "plant-water",
    name: "Grove Watering Rite",
    category: "Outdoor",
    difficulty: "quick",
    minutes: 3,
    xp: 40,
    coins: 10,
    goal: "Water indoor plants with a small, manageable watering can.",
    icon: "🪴",
  },
  {
    id: "recycle-sort",
    name: "Recycling Rune Sort",
    category: "Outdoor",
    difficulty: "quick",
    minutes: 4,
    xp: 50,
    coins: 12,
    goal: "Sort plastic, paper, and aluminum into the correct recycling bins.",
    icon: "♻️",
  },
  {
    id: "mail-run",
    name: "Mailbox Courier Run",
    category: "Outdoor",
    difficulty: "quick",
    minutes: 5,
    xp: 45,
    coins: 10,
    goal: "Walk to the mailbox and bring back letters and packages (teamwork welcome).",
    icon: "📬",
  },
  {
    id: "car-wash",
    name: "Wagon Wash Brigade",
    category: "Outdoor",
    difficulty: "epic",
    minutes: 15,
    xp: 100,
    coins: 25,
    goal: "Help wash the car — soapy sponge and rinse duty with a helper.",
    icon: "🚗",
  },
  {
    id: "holiday-stash",
    name: "Festival Pack & Stash",
    category: "Outdoor",
    difficulty: "epic",
    minutes: 15,
    xp: 95,
    coins: 22,
    goal: "Help put up or take down holiday decorations and store them in boxes.",
    icon: "🎄",
  },
];
